### ISSUE TITLE
importing to Zabbix

### ISSUE THREAD

**Issue by hubertsvk** [routepackets/zabbix#1]
Import Exchange 2016 - Services Template.xml **failed** 
Invalid tag "/zabbix_export/version": unsupported version number.

**Comment by routepackets** [comment]
What version number is the zabbix

**Comment by routepackets** [comment]
Apparently, you are trying to modify the Zabbix template which is built for 4.4 and not for the version you are working with.

Please update your Zabbix to Ver. 4.4 to use this template.

Thank you
